// Copyright © 2019-2023
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0

// mlkem -- ML-KEM-768 software baseline on Vortex.
//
// Runs one derandomized KEM round trip on the device against the library's
// known-answer vectors: the same d/z/m in, and pk/sk/ct/ss compared byte for
// byte with the expected output. That pins the result to FIPS 203 rather than
// to self-consistency -- a round trip can agree with itself while both halves
// are wrong. The KEM invariant (ss_enc == ss_dec) is still checked, because it
// localizes a failure to decapsulation when the vectors already disagree.
//
// The library is pq-code-package/mlkem-native, unmodified, configured through
// its own MLK_CONFIG_FILE hook. Nothing here is Vortex-specific except where
// the buffers live.

#include <vortex2.h>
#include "common.h"

// Auto-generated by the library and cross-checked against the reference
// implementation in its CI, selected by MLK_CONFIG_PARAMETER_SET. Host-side
// only: the device has no use for 4.7 KB of expected output.
#include "expected_test_vectors.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <unistd.h>
#include <vector>

#define CHECK(expr) do { \
    vx_result_t _r = (expr); \
    if (_r != VX_SUCCESS) { \
        std::fprintf(stderr, "FAIL %s:%d: '%s' returned %s\n", \
                     __FILE__, __LINE__, #expr, vx_result_string(_r)); \
        std::exit(1); \
    } \
} while (0)

// Unbuffered: under an RTL simulator a run can take minutes, and the last line
// printed is the only clue to where a hang is.
#define STEP(msg) do { std::printf("[mlkem] %s\n", (msg)); std::fflush(stdout); } while (0)

namespace {
const char* kernel_file = "kernel.vxbin";

void parse_args(int argc, char** argv) {
    int c;
    while ((c = getopt(argc, argv, "k:h")) != -1) {
        switch (c) {
            case 'k': kernel_file = optarg; break;
            default:
                std::cout << "Usage: [-k kernel] [-h]" << std::endl;
                std::exit(c == 'h' ? 0 : -1);
        }
    }
}

int compare(const char* what, const uint8_t* got, const uint8_t* want, size_t n) {
    if (std::memcmp(got, want, n) == 0)
        return 0;
    size_t i = 0;
    while (i < n && got[i] == want[i]) ++i;
    std::printf("*** %s differs at byte %zu: got %02x want %02x\n",
                what, i, got[i], want[i]);
    return 1;
}
} // namespace

int main(int argc, char** argv) {
    parse_args(argc, argv);

    std::cout << "ML-KEM-" << MLK_CONFIG_PARAMETER_SET
              << "  pk=" << MLKEM_PK_BYTES
              << " sk=" << MLKEM_SK_BYTES
              << " ct=" << MLKEM_CT_BYTES
              << " ss=" << MLKEM_SS_BYTES << std::endl;

    STEP("device_open");
    vx_device_h dev = nullptr;
    CHECK(vx_device_open(0, &dev));

    vx_queue_info_t qi = { sizeof(qi), nullptr, VX_QUEUE_PRIORITY_NORMAL, 0 };
    vx_queue_h q = nullptr;
    CHECK(vx_queue_create(dev, &qi, &q));

    STEP("buffer_create");
    struct { vx_buffer_h h; uint64_t bytes; int write; } bufs[] = {
        { nullptr, 2 * MLKEM_SYM_BYTES,          0 },  // coins_kp   (host -> dev)
        { nullptr, MLKEM_SYM_BYTES,              0 },  // coins_enc  (host -> dev)
        { nullptr, MLKEM_PK_BYTES,               1 },
        { nullptr, MLKEM_SK_BYTES,               1 },
        { nullptr, MLKEM_CT_BYTES,               1 },
        { nullptr, MLKEM_SS_BYTES,               1 },  // ss_enc
        { nullptr, MLKEM_SS_BYTES,               1 },  // ss_dec
        { nullptr, MLKEM_ST_COUNT * sizeof(int32_t), 1 },
        { nullptr, MLKEM_CY_COUNT * sizeof(uint64_t), 1 },
    };
    for (auto& b : bufs)
        CHECK(vx_buffer_create(dev, b.bytes, b.write ? VX_MEM_WRITE : VX_MEM_READ, &b.h));

    kernel_arg_t arg{};
    uint64_t* slots[] = { &arg.coins_kp_addr, &arg.coins_enc_addr, &arg.pk_addr,
                          &arg.sk_addr, &arg.ct_addr, &arg.ss_enc_addr,
                          &arg.ss_dec_addr, &arg.status_addr,
                          &arg.cycles_addr };
    for (size_t i = 0; i < sizeof(bufs) / sizeof(bufs[0]); ++i)
        CHECK(vx_buffer_address(bufs[i].h, slots[i]));

    STEP("module_load");
    vx_module_h mod = nullptr;
    vx_kernel_h kern = nullptr;
    CHECK(vx_module_load_file(dev, kernel_file, &mod));
    CHECK(vx_module_get_kernel(mod, "main", &kern));

    STEP("upload coins");
    // keypair_derand consumes d || z; enc_derand consumes m.
    std::vector<uint8_t> h_coins_kp(2 * MLKEM_SYM_BYTES);
    std::vector<uint8_t> h_coins_enc(MLKEM_SYM_BYTES);
    std::memcpy(h_coins_kp.data(),                   test_vector_d, MLKEM_SYM_BYTES);
    std::memcpy(h_coins_kp.data() + MLKEM_SYM_BYTES, test_vector_z, MLKEM_SYM_BYTES);
    std::memcpy(h_coins_enc.data(),                  test_vector_m, MLKEM_SYM_BYTES);
    CHECK(vx_enqueue_write(q, bufs[0].h, 0, h_coins_kp.data(), h_coins_kp.size(), 0, nullptr, nullptr));
    CHECK(vx_enqueue_write(q, bufs[1].h, 0, h_coins_enc.data(), h_coins_enc.size(), 0, nullptr, nullptr));

    // Seed the outputs with a value the kernel never writes, so a "match" that
    // is really a buffer nobody touched cannot pass as success.
    std::vector<int32_t> h_status(MLKEM_ST_COUNT, -12345);
    std::vector<uint8_t> h_ss_enc(MLKEM_SS_BYTES, 0xAA);
    std::vector<uint8_t> h_ss_dec(MLKEM_SS_BYTES, 0x55);
    CHECK(vx_enqueue_write(q, bufs[7].h, 0, h_status.data(),  h_status.size() * sizeof(int32_t), 0, nullptr, nullptr));
    CHECK(vx_enqueue_write(q, bufs[5].h, 0, h_ss_enc.data(),  h_ss_enc.size(), 0, nullptr, nullptr));
    CHECK(vx_enqueue_write(q, bufs[6].h, 0, h_ss_dec.data(),  h_ss_dec.size(), 0, nullptr, nullptr));

    STEP("launch");
    vx_launch_info_t li{};
    li.struct_size  = sizeof(li);
    li.kernel       = kern;
    li.args_host    = &arg;
    li.args_size    = sizeof(arg);
    li.ndim         = 1;
    li.grid_dim[0]  = 1;
    li.block_dim[0] = 1;
    vx_event_h launch_ev = nullptr;
    CHECK(vx_enqueue_launch(q, &li, 0, nullptr, &launch_ev));

    STEP("readback");
    std::vector<uint8_t>  h_pk(MLKEM_PK_BYTES), h_sk(MLKEM_SK_BYTES), h_ct(MLKEM_CT_BYTES);
    std::vector<uint64_t> h_cycles(MLKEM_CY_COUNT, 0);
    struct { void* dst; int buf; uint64_t bytes; vx_event_h ev; } reads[] = {
        { h_status.data(), 7, h_status.size() * sizeof(int32_t),  nullptr },
        { h_cycles.data(), 8, h_cycles.size() * sizeof(uint64_t), nullptr },
        { h_pk.data(),     2, MLKEM_PK_BYTES, nullptr },
        { h_sk.data(),     3, MLKEM_SK_BYTES, nullptr },
        { h_ct.data(),     4, MLKEM_CT_BYTES, nullptr },
        { h_ss_enc.data(), 5, MLKEM_SS_BYTES, nullptr },
        { h_ss_dec.data(), 6, MLKEM_SS_BYTES, nullptr },
    };
    for (auto& r : reads)
        CHECK(vx_enqueue_read(q, r.dst, bufs[r.buf].h, 0, r.bytes, 1, &launch_ev, &r.ev));

    STEP("wait");
    for (auto& r : reads)
        CHECK(vx_event_wait_value(r.ev, 1, VX_TIMEOUT_INFINITE));

    STEP("verify");
    int errors = 0;
    static const char* step_name[MLKEM_ST_COUNT] = { "keypair_derand", "enc_derand", "dec" };
    for (int i = 0; i < MLKEM_ST_COUNT; ++i) {
        if (h_status[i] != 0) {
            std::printf("*** %s returned %d%s\n", step_name[i], h_status[i],
                        h_status[i] == -12345 ? "  (kernel never ran)" : "");
            ++errors;
        }
    }
    if (errors == 0) {
        errors += compare("pk", h_pk.data(), test_vector_pk, MLKEM_PK_BYTES);
        errors += compare("sk", h_sk.data(), test_vector_sk, MLKEM_SK_BYTES);
        errors += compare("ct", h_ct.data(), test_vector_ct, MLKEM_CT_BYTES);
        errors += compare("ss", h_ss_enc.data(), test_vector_ss, MLKEM_SS_BYTES);
    }
    if (errors == 0 && std::memcmp(h_ss_enc.data(), h_ss_dec.data(), MLKEM_SS_BYTES) != 0) {
        std::printf("*** shared secrets differ\n    enc:");
        for (int i = 0; i < 8; ++i) std::printf(" %02x", h_ss_enc[i]);
        std::printf("\n    dec:");
        for (int i = 0; i < 8; ++i) std::printf(" %02x", h_ss_dec[i]);
        std::printf("\n");
        ++errors;
    }

    // Device cycles per phase. Single thread, so this is the software baseline
    // every later speedup divides into.
    for (int i = 0; i < MLKEM_CY_COUNT; ++i)
        if (h_cycles[i] == 0) { std::printf("*** phase %d measured zero cycles\n", i); ++errors; }
    const uint64_t total = h_cycles[MLKEM_CY_KEYPAIR] + h_cycles[MLKEM_CY_ENCAPS]
                         + h_cycles[MLKEM_CY_DECAPS];
    std::printf("CYCLES: keypair=%llu encaps=%llu decaps=%llu total=%llu\n",
                (unsigned long long)h_cycles[MLKEM_CY_KEYPAIR],
                (unsigned long long)h_cycles[MLKEM_CY_ENCAPS],
                (unsigned long long)h_cycles[MLKEM_CY_DECAPS],
                (unsigned long long)total);

    for (auto& r : reads) vx_event_release(r.ev);
    vx_event_release(launch_ev);
    for (auto& b : bufs) vx_buffer_release(b.h);
    vx_kernel_release(kern);
    vx_module_release(mod);
    vx_queue_release(q);
    vx_device_release(dev);

    if (errors != 0) { std::cout << "FAILED!" << std::endl; return 1; }
    std::cout << "PASSED!" << std::endl;
    return 0;
}
