// Copyright © 2019-2023
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0

// mlkem -- ML-KEM-768 software baseline on Vortex.
//
// Runs one derandomized KEM round trip on the device against the library's
// known-answer vectors: the same d/z/m in, and pk/sk/ct/ss compared byte for
// byte with the expected output. That pins the result to FIPS 203 rather than
// to self-consistency -- a round trip can agree with itself while both halves
// are wrong. The KEM invariant (ss_enc == ss_dec) is still checked, because it
// localizes a failure to decapsulation when the vectors already disagree.
//
// The library is pq-code-package/mlkem-native, unmodified, configured through
// its own MLK_CONFIG_FILE hook. Nothing here is Vortex-specific except where
// the buffers live.

#include <vortex2.h>
#include "common.h"
#include "pqc_config.h"
#include "pqc_stack.h"
#include "mlk_vortex_alloc.h"

// Auto-generated by the library and cross-checked against the reference
// implementation in its CI, selected by MLK_CONFIG_PARAMETER_SET. Host-side
// only: the device has no use for 4.7 KB of expected output.
#include "expected_test_vectors.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <unistd.h>
#include <vector>

#define CHECK(expr) do { \
    vx_result_t _r = (expr); \
    if (_r != VX_SUCCESS) { \
        std::fprintf(stderr, "FAIL %s:%d: '%s' returned %s\n", \
                     __FILE__, __LINE__, #expr, vx_result_string(_r)); \
        std::exit(1); \
    } \
} while (0)

// Unbuffered: under an RTL simulator a run can take minutes, and the last line
// printed is the only clue to where a hang is.
#define STEP(msg) do { std::printf("[mlkem] %s\n", (msg)); std::fflush(stdout); } while (0)

namespace {
const char* kernel_file = "kernel.vxbin";
uint32_t requests = 1;

void parse_args(int argc, char** argv) {
    int c;
    while ((c = getopt(argc, argv, "k:b:h")) != -1) {
        switch (c) {
            case 'k': kernel_file = optarg; break;
            case 'b': requests = (uint32_t)std::atoi(optarg); break;
            default:
                std::cout << "Usage: [-k kernel] [-b requests] [-h]" << std::endl;
                std::exit(c == 'h' ? 0 : -1);
        }
    }
    if (requests < 1) { std::fprintf(stderr, "FAIL: -b must be >= 1\n"); std::exit(-1); }
}

int compare(const char* what, const uint8_t* got, const uint8_t* want, size_t n) {
    if (std::memcmp(got, want, n) == 0)
        return 0;
    size_t i = 0;
    while (i < n && got[i] == want[i]) ++i;
    std::printf("*** %s differs at byte %zu: got %02x want %02x\n",
                what, i, got[i], want[i]);
    return 1;
}
} // namespace

int main(int argc, char** argv) {
    parse_args(argc, argv);

    std::cout << "ML-KEM-" << MLK_CONFIG_PARAMETER_SET
              << "  pk=" << MLKEM_PK_BYTES
              << " sk=" << MLKEM_SK_BYTES
              << " ct=" << MLKEM_CT_BYTES
              << " ss=" << MLKEM_SS_BYTES << std::endl;

    STEP("device_open");
    vx_device_h dev = nullptr;
    CHECK(vx_device_open(0, &dev));
    const pqc::config cfg = pqc::print_config(dev, requests, 1);
    if (pqc::require_slots(cfg, requests, 1) != 0) { vx_device_release(dev); return -1; }

    vx_queue_info_t qi = { sizeof(qi), nullptr, VX_QUEUE_PRIORITY_NORMAL, 0 };
    vx_queue_h q = nullptr;
    CHECK(vx_queue_create(dev, &qi, &q));

    STEP("buffer_create");
    struct { vx_buffer_h h; uint64_t bytes; int write; } bufs[] = {
        { nullptr, 2 * MLKEM_SYM_BYTES,          0 },  // coins_kp   (host -> dev)
        { nullptr, MLKEM_SYM_BYTES,              0 },  // coins_enc  (host -> dev)
        { nullptr, (uint64_t)requests * MLKEM_PK_BYTES,               1 },
        { nullptr, (uint64_t)requests * MLKEM_SK_BYTES,               1 },
        { nullptr, (uint64_t)requests * MLKEM_CT_BYTES,               1 },
        { nullptr, (uint64_t)requests * MLKEM_SS_BYTES,               1 },  // ss_enc
        { nullptr, (uint64_t)requests * MLKEM_SS_BYTES,               1 },  // ss_dec
        { nullptr, (uint64_t)requests * MLKEM_ST_COUNT * sizeof(int32_t),  1 },
        { nullptr, (uint64_t)requests * MLKEM_CY_COUNT * sizeof(uint64_t), 1 },
        { nullptr, (uint64_t)requests * MLKEM_PR_COUNT * sizeof(uint32_t), 1 },
    };
    for (auto& b : bufs)
        CHECK(vx_buffer_create(dev, b.bytes, b.write ? VX_MEM_WRITE : VX_MEM_READ, &b.h));

    kernel_arg_t arg{};
    uint64_t* slots[] = { &arg.coins_kp_addr, &arg.coins_enc_addr, &arg.pk_addr,
                          &arg.sk_addr, &arg.ct_addr, &arg.ss_enc_addr,
                          &arg.ss_dec_addr, &arg.status_addr,
                          &arg.cycles_addr, &arg.probe_addr };
    for (size_t i = 0; i < sizeof(bufs) / sizeof(bufs[0]); ++i)
        CHECK(vx_buffer_address(bufs[i].h, slots[i]));
    arg.requests = requests;

    STEP("module_load");
    vx_module_h mod = nullptr;
    vx_kernel_h kern = nullptr;
    CHECK(vx_module_load_file(dev, kernel_file, &mod));
    CHECK(vx_module_get_kernel(mod, "main", &kern));

    STEP("upload coins");
    // keypair_derand consumes d || z; enc_derand consumes m.
    std::vector<uint8_t> h_coins_kp(2 * MLKEM_SYM_BYTES);
    std::vector<uint8_t> h_coins_enc(MLKEM_SYM_BYTES);
    std::memcpy(h_coins_kp.data(),                   test_vector_d, MLKEM_SYM_BYTES);
    std::memcpy(h_coins_kp.data() + MLKEM_SYM_BYTES, test_vector_z, MLKEM_SYM_BYTES);
    std::memcpy(h_coins_enc.data(),                  test_vector_m, MLKEM_SYM_BYTES);
    CHECK(vx_enqueue_write(q, bufs[0].h, 0, h_coins_kp.data(), h_coins_kp.size(), 0, nullptr, nullptr));
    CHECK(vx_enqueue_write(q, bufs[1].h, 0, h_coins_enc.data(), h_coins_enc.size(), 0, nullptr, nullptr));

    // Seed the outputs with a value the kernel never writes, so a "match" that
    // is really a buffer nobody touched cannot pass as success.
    std::vector<int32_t> h_status(requests * MLKEM_ST_COUNT, -12345);
    std::vector<uint8_t> h_ss_enc(requests * MLKEM_SS_BYTES, 0xAA);
    std::vector<uint8_t> h_ss_dec(requests * MLKEM_SS_BYTES, 0x55);
    CHECK(vx_enqueue_write(q, bufs[7].h, 0, h_status.data(),  h_status.size() * sizeof(int32_t), 0, nullptr, nullptr));
    CHECK(vx_enqueue_write(q, bufs[5].h, 0, h_ss_enc.data(),  h_ss_enc.size(), 0, nullptr, nullptr));
    CHECK(vx_enqueue_write(q, bufs[6].h, 0, h_ss_dec.data(),  h_ss_dec.size(), 0, nullptr, nullptr));

    STEP("launch");
    vx_launch_info_t li{};
    li.struct_size  = sizeof(li);
    li.kernel       = kern;
    li.args_host    = &arg;
    li.args_size    = sizeof(arg);
    li.ndim         = 1;
    li.grid_dim[0]  = requests;
    li.block_dim[0] = 1;
    vx_event_h launch_ev = nullptr;
    CHECK(vx_enqueue_launch(q, &li, 0, nullptr, &launch_ev));

    STEP("readback");
    std::vector<uint8_t>  h_pk(requests * MLKEM_PK_BYTES), h_sk(requests * MLKEM_SK_BYTES),
                          h_ct(requests * MLKEM_CT_BYTES);
    std::vector<uint64_t> h_cycles(requests * MLKEM_CY_COUNT, 0);
    std::vector<uint32_t> h_probe(requests * MLKEM_PR_COUNT, 0);
    struct { void* dst; int buf; uint64_t bytes; vx_event_h ev; } reads[] = {
        { h_status.data(), 7, h_status.size() * sizeof(int32_t),  nullptr },
        { h_cycles.data(), 8, h_cycles.size() * sizeof(uint64_t), nullptr },
        { h_pk.data(),     2, (uint64_t)requests * MLKEM_PK_BYTES, nullptr },
        { h_sk.data(),     3, (uint64_t)requests * MLKEM_SK_BYTES, nullptr },
        { h_ct.data(),     4, (uint64_t)requests * MLKEM_CT_BYTES, nullptr },
        { h_ss_enc.data(), 5, (uint64_t)requests * MLKEM_SS_BYTES, nullptr },
        { h_ss_dec.data(), 6, (uint64_t)requests * MLKEM_SS_BYTES, nullptr },
        { h_probe.data(),  9, h_probe.size() * sizeof(uint32_t), nullptr },
    };
    for (auto& r : reads)
        CHECK(vx_enqueue_read(q, r.dst, bufs[r.buf].h, 0, r.bytes, 1, &launch_ev, &r.ev));

    STEP("wait");
    for (auto& r : reads)
        CHECK(vx_event_wait_value(r.ev, 1, VX_TIMEOUT_INFINITE));

    STEP("verify");
    int errors = 0;
    static const char* step_name[MLKEM_ST_COUNT] = { "keypair_derand", "enc_derand", "dec" };

    // Every request runs the same coins, so every request must reproduce the
    // same published vector. That is the point of using identical inputs: a
    // request that strays into a neighbour's workspace diverges from the KAT,
    // whereas with per-request coins the whole batch could agree on the same
    // wrong answer and still look self-consistent.
    for (uint32_t r = 0; r < requests; ++r) {
        const int32_t* st = &h_status[r * MLKEM_ST_COUNT];
        int req_err = 0;
        for (int i = 0; i < MLKEM_ST_COUNT; ++i) {
            if (st[i] != 0) {
                std::printf("*** request %u: %s returned %d%s\n", r, step_name[i], st[i],
                            st[i] == -12345 ? "  (kernel never ran)" : "");
                ++req_err;
            }
        }
        if (req_err == 0) {
            char what[32];
            std::snprintf(what, sizeof(what), "req%u.pk", r);
            req_err += compare(what, &h_pk[r * MLKEM_PK_BYTES], test_vector_pk, MLKEM_PK_BYTES);
            std::snprintf(what, sizeof(what), "req%u.sk", r);
            req_err += compare(what, &h_sk[r * MLKEM_SK_BYTES], test_vector_sk, MLKEM_SK_BYTES);
            std::snprintf(what, sizeof(what), "req%u.ct", r);
            req_err += compare(what, &h_ct[r * MLKEM_CT_BYTES], test_vector_ct, MLKEM_CT_BYTES);
            std::snprintf(what, sizeof(what), "req%u.ss", r);
            req_err += compare(what, &h_ss_enc[r * MLKEM_SS_BYTES], test_vector_ss, MLKEM_SS_BYTES);
            if (std::memcmp(&h_ss_enc[r * MLKEM_SS_BYTES],
                            &h_ss_dec[r * MLKEM_SS_BYTES], MLKEM_SS_BYTES) != 0) {
                std::printf("*** request %u: shared secrets differ\n", r);
                ++req_err;
            }
        }
        errors += req_err;
    }

    // Stack watermark. An overflow here is invisible at run time -- the RAM has
    // no ACL and pages in on demand, so hart 0 running past its slab just
    // scribbles on idle hart 1 and every KAT still matches. These checks are
    // the only thing standing between that and a silently wrong measurement.
    uint32_t stack_max = 0, arena_max = 0, arena_fail = 0, span = 0;
    for (uint32_t r = 0; r < requests; ++r) {
        const uint32_t* pr = &h_probe[r * MLKEM_PR_COUNT];
        if (pr[MLKEM_PR_STACK_PEAK] == 0) {
            std::printf("*** request %u: stack watermark is zero -- the probe never ran\n", r);
            ++errors;
        } else if (pr[MLKEM_PR_STACK_PEAK] >= pr[MLKEM_PR_STACK_SPAN]) {
            std::printf("*** request %u: stack peak %u B filled its whole %u B paintable"
                        " slab -- it overflowed into the next hart\n",
                        r, pr[MLKEM_PR_STACK_PEAK], pr[MLKEM_PR_STACK_SPAN]);
            ++errors;
        }
        if (pr[MLKEM_PR_ARENA_FAIL] != 0) {
            std::printf("*** request %u: arena exhausted %u times -- raise MLK_ARENA_BYTES\n",
                        r, pr[MLKEM_PR_ARENA_FAIL]);
            ++errors;
        }
        if (pr[MLKEM_PR_ARENA_PEAK] == 0) {
            std::printf("*** request %u: arena peak is zero -- MLK_CUSTOM_ALLOC was never"
                        " reached, so this is not the build being measured\n", r);
            ++errors;
        }
        if (pr[MLKEM_PR_STACK_PEAK] > stack_max) stack_max = pr[MLKEM_PR_STACK_PEAK];
        if (pr[MLKEM_PR_ARENA_PEAK] > arena_max) arena_max = pr[MLKEM_PR_ARENA_PEAK];
        arena_fail += pr[MLKEM_PR_ARENA_FAIL];
        span = pr[MLKEM_PR_STACK_SPAN];
    }
    std::printf("STACK: peak=%u of %u paintable (slab %u)   ARENA: peak=%u of %u fail=%u"
                "   (max over %u requests)\n",
                stack_max, span, (unsigned)PQC_SLAB_BYTES,
                arena_max, (unsigned)MLK_ARENA_BYTES, arena_fail, requests);

    // Per-request device cycles. These are concurrent, not additive: request r
    // measures its own vx_rdcycle span, and the spans overlap. The batch's cost
    // is the device cycle count from --perf, not the sum of these. What the
    // spread says is how much the requests interfered with each other -- at
    // M=1 min and max are the same number by construction.
    uint64_t tot_min = ~0ull, tot_max = 0, tot_sum = 0;
    for (uint32_t r = 0; r < requests; ++r) {
        const uint64_t* cy = &h_cycles[r * MLKEM_CY_COUNT];
        for (int i = 0; i < MLKEM_CY_COUNT; ++i)
            if (cy[i] == 0) {
                std::printf("*** request %u: phase %d measured zero cycles\n", r, i);
                ++errors;
            }
        const uint64_t t = cy[MLKEM_CY_KEYPAIR] + cy[MLKEM_CY_ENCAPS] + cy[MLKEM_CY_DECAPS];
        if (t < tot_min) tot_min = t;
        if (t > tot_max) tot_max = t;
        tot_sum += t;
    }
    const uint64_t* cy0 = &h_cycles[0];
    std::printf("CYCLES: keypair=%llu encaps=%llu decaps=%llu total=%llu   (request 0)\n",
                (unsigned long long)cy0[MLKEM_CY_KEYPAIR],
                (unsigned long long)cy0[MLKEM_CY_ENCAPS],
                (unsigned long long)cy0[MLKEM_CY_DECAPS],
                (unsigned long long)(cy0[MLKEM_CY_KEYPAIR] + cy0[MLKEM_CY_ENCAPS]
                                     + cy0[MLKEM_CY_DECAPS]));
    if (requests > 1)
        std::printf("REQUESTS: n=%u  per-request total min=%llu mean=%llu max=%llu"
                    "  spread=%.1f%%\n", requests,
                    (unsigned long long)tot_min, (unsigned long long)(tot_sum / requests),
                    (unsigned long long)tot_max,
                    100.0 * (double)(tot_max - tot_min) / (double)tot_min);

    for (auto& r : reads) vx_event_release(r.ev);
    // Device-level counters. The per-request spans above overlap, so this is
    // the only figure that is the batch's actual cost, and IPC is the column
    // that says whether a batch stopped scaling on issue or on memory.
    vx_device_dump_perf(dev, stdout);

    vx_event_release(launch_ev);
    for (auto& b : bufs) vx_buffer_release(b.h);
    vx_kernel_release(kern);
    vx_module_release(mod);
    vx_queue_release(q);
    vx_device_release(dev);

    if (errors != 0) { std::cout << "FAILED!" << std::endl; return 1; }
    std::cout << "PASSED!" << std::endl;
    return 0;
}
